import { APP_VERSION } from '../config/app-config.js';
import { analyze, observedLabel, sfaLabel, legacySfaLabel, exactSfaCode, analysisReasonStatus } from '../domain/analysis-engine.js';
import { normalizedRecoveryStatus, normalizedCaptureType, safeLegacyExactCode } from '../domain/reason-engine.js';
import { num } from '../config/utils.js';

function download(name,content,type='text/plain;charset=utf-8'){const blob=new Blob([content],{type});const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function xmlEscape(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function cell(v){const type=typeof v==='number'?'Number':'String';return `<Cell><Data ss:Type="${type}">${xmlEscape(v)}</Data></Cell>`}
function sheet(name,rows){return `<Worksheet ss:Name="${name.slice(0,31).replace(/[\\/?*\[\]:]/g,'_')}"><Table>${rows.map(r=>`<Row>${r.map(cell).join('')}</Row>`).join('')}</Table></Worksheet>`}
const avg=values=>{const v=values.filter(x=>Number.isFinite(x)&&x>=0);return v.length?v.reduce((s,x)=>s+x,0)/v.length:null};
const labelByCode=(taxonomy,code,language='id')=>{const r=taxonomy.find(x=>x.reason_code===code);return r?(language==='id'?r.reason_label_id:r.reason_label_en):(code||'')};
const method=c=>c.call_method||'VISIT';

export function buildDetailedWorkbook({visits=[],calls=[],taxonomy=[],profiles=[],reasonDetails=[],stockItems=[],recoveryAttempts=[],photos=[],language='id'}){
  const a=analyze(visits,calls,taxonomy,language),pmap=Object.fromEntries(profiles.map(p=>[p.id,p])),vmap=Object.fromEntries(visits.map(v=>[v.id,v]));
  const activeCalls=calls.filter(x=>!x.is_deleted),detailMap=Object.fromEntries(reasonDetails.map(x=>[x.call_id,x]));
  const recoveredByCall={};for(const x of recoveryAttempts.filter(x=>x.outcome==='RECOVERED_EC')){const prev=recoveredByCall[x.call_id];if(!prev||String(x.attempted_at)>String(prev.attempted_at))recoveredByCall[x.call_id]=x}

  const rawHeader=['Visit ID','Call ID','Visit Date','JOVIS','JOVIS User ID','Depot','Salesman','Salesman ID','Visit Start Time','Visit End Time','Visit Status','Call Method','Call Timestamp','Check-in At','Checkout At','Duration Seconds','Duration Minutes','Check-in Latitude','Check-in Longitude','Check-in Accuracy (m)','Checkout Latitude','Checkout Longitude','Checkout Accuracy (m)','Kode Toko','Nama Toko','JKS / Off Route / Remote','Initial Result','Initial Omzet EC','Recovered Outcome','Recovered Omzet','Observed Real Reason','Observed Reason Code','Custom Real Reason','Evidence','SFA Reason Exact','SFA Exact Code','SFA Legacy Reason','SFA Legacy Code','SFA Capture Type','SFA Recovery Status','Reason Alignment','Why SFA Reason Selected','Planned Revisit','Can Revisit Earlier','Reason Determining Follow-up Timing','Quick Note','Created At','Updated At'];
  const rawRow=c=>{const v=vmap[c.visit_id]||{},p=pmap[c.jovis_user_id]||{},dur=Number(c.duration_seconds),exact=exactSfaCode(c)||safeLegacyExactCode(c),rec=recoveredByCall[c.id];return [v.id||c.visit_id,c.id,v.visit_date||'',p.display_name||'',c.jovis_user_id,v.depot||'',v.salesman_name||'',v.salesman_id||'',v.start_time||'',v.end_time||'',v.status||'',method(c),c.call_timestamp||'',c.checkin_at||'',c.checkout_at||'',Number.isFinite(dur)?dur:'',Number.isFinite(dur)?dur/60:'',c.checkin_latitude??'',c.checkin_longitude??'',c.checkin_accuracy_m??'',c.checkout_latitude??'',c.checkout_longitude??'',c.checkout_accuracy_m??'',c.outlet_id||'',c.outlet_name||'',c.route_status||'',c.result||'',c.result==='EC'?num(c.omzet):'',rec?'RECOVERED_EC':'',rec?num(rec.omzet):'',c.result==='NON_EC'?observedLabel(c,taxonomy,language):'',c.observed_reason_code||'',c.custom_real_reason||'',c.evidence||'',c.result==='NON_EC'?(exact?labelByCode(taxonomy,exact,language):'UNRESOLVED'):'',exact||'',c.result==='NON_EC'?legacySfaLabel(c,taxonomy,language):'',normalizedCaptureType(c)==='LEGACY'?(c.sfa_reason_code||''):'',c.result==='NON_EC'?(normalizedCaptureType(c)||''):'',c.result==='NON_EC'?(normalizedRecoveryStatus(c)||''):'',c.result==='NON_EC'?(analysisReasonStatus(c)||''):'',c.sfa_selection_reason||'',c.revisit_plan||'',c.can_revisit_earlier||'',c.followup_timing_reason||'',c.quick_note||'',c.created_at||'',c.updated_at||'']};
  const rawRows=[rawHeader,...activeCalls.map(rawRow)],nonEc=[rawHeader,...activeCalls.filter(c=>method(c)==='VISIT'&&c.result==='NON_EC').map(rawRow)];

  const acc=[['SFA Reason Exact','Cases','Comparable Cases','Match','Partial','Mismatch','Unclear','Non-causal','Taxonomy Gap','Unresolved','Exact Match %','Mismatch %'],...Object.entries(a.bySfa).map(([code,x])=>[a.sfaLabels[code]||code,x.n,x.evaluable,x.MATCH,x.PARTIAL,x.MISMATCH,x.UNCLEAR,x.NON_CAUSAL,x.TAXONOMY_GAP,x.UNRESOLVED,x.exactRate,x.evaluable?x.mismatchRate:''])];
  const okeys=Object.keys(a.observedCounts),skeys=Object.keys(a.sfaCounts),matrix=[['SFA Exact \\ Actual',...okeys.map(k=>a.observedLabels[k]||k)],...skeys.map(s=>[a.sfaLabels[s]||s,...okeys.map(o=>a.matrix[s]?.[o]||0)])];
  const unmapped=[['Raw Actual Reason','Frequency','JOVIS','Depot','Salesman','Kode Toko','Nama Toko','Evidence','Call ID']];for(const cr of Object.values(a.customReasons).sort((x,y)=>y.count-x.count)){for(const c of cr.cases){const v=vmap[c.visit_id]||{},p=pmap[c.jovis_user_id]||{};unmapped.push([cr.label,cr.count,p.display_name||'',v.depot||'',v.salesman_name||'',c.outlet_id||'',c.outlet_name||'',c.evidence||'',c.id])}}
  const follow=[['Visit ID','Call ID','JOVIS','Kode Toko','Nama Toko','Actual Reason','Planned Revisit','Can Revisit Earlier','Reason Determining Timing','Recoverable Today','Preferred Recovery Channel','Best Follow-up Time'],...activeCalls.filter(c=>method(c)==='VISIT'&&c.result==='NON_EC').map(c=>{const d=detailMap[c.id]||{};return[c.visit_id,c.id,pmap[c.jovis_user_id]?.display_name||'',c.outlet_id||'',c.outlet_name||'',observedLabel(c,taxonomy,language),c.revisit_plan||'',c.can_revisit_earlier||'',c.followup_timing_reason||'',d.recoverable_today||'',d.preferred_recovery_channel||'',d.best_followup_time||'']})];
  const vs=[['Visit ID','Date','JOVIS','Depot','Salesman','Start','End','Status','Visit SC','Visit EC','Visit Non-EC','Visit EC/SC %','Visit Omzet','Pure WA EC','Pure WA Omzet','Avg Visit Duration Seconds'],...a.visitSummaries.map(x=>{const vc=activeCalls.filter(c=>c.visit_id===x.visit.id&&method(c)==='VISIT'),d=avg(vc.map(c=>Number(c.duration_seconds)));return[x.visit.id,x.visit.visit_date,pmap[x.visit.jovis_user_id]?.display_name||'',x.visit.depot,x.visit.salesman_name,x.visit.start_time,x.visit.end_time||'',x.visit.status,x.sc,x.ec,x.ne,x.ecsc,x.revenue,x.waEc||0,x.waRevenue||0,d??'']})];
  const dwell=[['Visit ID','Call ID','Date','JOVIS','Depot','Salesman','Kode Toko','Nama Toko','Result','Check-in At','Checkout At','Duration Seconds','Check-in Latitude','Check-in Longitude','Check-in Accuracy (m)','Checkout Latitude','Checkout Longitude','Checkout Accuracy (m)'],...activeCalls.filter(c=>method(c)==='VISIT').map(c=>{const v=vmap[c.visit_id]||{},p=pmap[c.jovis_user_id]||{};return[c.visit_id,c.id,v.visit_date||'',p.display_name||'',v.depot||'',v.salesman_name||'',c.outlet_id||'',c.outlet_name||'',c.result||'',c.checkin_at||'',c.checkout_at||'',c.duration_seconds??'',c.checkin_latitude??'',c.checkin_longitude??'',c.checkin_accuracy_m??'',c.checkout_latitude??'',c.checkout_longitude??'',c.checkout_accuracy_m??'']})];
  const sfaRecovery=[['Call ID','JOVIS','Kode Toko','Nama Toko','Observed Reason','Legacy SFA Reason','Legacy SFA Code','Exact SFA Reason','Exact SFA Code','Capture Type','Recovery Status','Alignment','Evidence'],...activeCalls.filter(c=>c.result==='NON_EC'&&normalizedCaptureType(c)==='LEGACY').map(c=>{const exact=exactSfaCode(c)||safeLegacyExactCode(c);return[c.id,pmap[c.jovis_user_id]?.display_name||'',c.outlet_id||'',c.outlet_name||'',observedLabel(c,taxonomy,language),legacySfaLabel(c,taxonomy,language),c.sfa_reason_code||'',exact?labelByCode(taxonomy,exact,language):'',exact||'','LEGACY',normalizedRecoveryStatus(c)||'',analysisReasonStatus(c)||'',c.evidence||'']})];

  const reasonDetailHeader=['Call ID','JOVIS','Kode Toko','Nama Toko','Actual Reason','Recoverable Today','Preferred Recovery Channel','Best Follow-up Time','PIC Status','PIC Expected Return','Closed Status','Closed Expected Open','Financial Status','Cash Available When','Partial Order Possible','Refusal Driver','Expected Next Order','Price Issue Type','Price Detail','Product Issue Type','Affected Products','External Supplier','External Supplier Driver','Normal Buying Cycle','Last Order Date','Last Delivery Date','Salesman Oversized/Bombing Claim','Salesman Claim Explanation','Detail Notes','Source Version'];
  const reasonDetailRows=[reasonDetailHeader,...reasonDetails.map(d=>{const c=activeCalls.find(x=>x.id===d.call_id)||{};return[d.call_id,pmap[d.jovis_user_id]?.display_name||'',c.outlet_id||'',c.outlet_name||'',c.result==='NON_EC'?observedLabel(c,taxonomy,language):'',d.recoverable_today||'',d.preferred_recovery_channel||'',d.best_followup_time||'',d.pic_status||'',d.pic_expected_return||'',d.closed_status||'',d.closed_expected_open||'',d.financial_status||'',d.cash_available_when||'',d.partial_order_possible||'',d.refusal_driver||'',d.expected_next_order||'',d.price_issue_type||'',d.price_detail||'',d.product_issue_type||'',d.affected_products||'',d.external_supplier_name||'',d.external_supplier_driver||'',d.normal_buying_cycle||'',d.last_order_date||'',d.last_delivery_date||'',d.salesman_bombing_claim||'',d.salesman_bombing_reason||'',d.detail_notes||'',d.source_version||'']} )];
  const stockRows=[['Stock Item ID','Call ID','JOVIS','Kode Toko','Nama Toko','Product / SKU','Stock Level','Qty Note','Notes'],...stockItems.map(x=>{const c=activeCalls.find(c=>c.id===x.call_id)||{};return[x.id,x.call_id,pmap[x.jovis_user_id]?.display_name||'',c.outlet_id||'',c.outlet_name||'',x.product_name||'',x.stock_level||'',x.qty_note||'',x.notes||'']})];
  const recoveryRows=[['Recovery ID','Call ID','Visit ID','Date','JOVIS','Kode Toko','Nama Toko','Initial Actual Reason','Attempted At','Channel','Outcome','Recovered Omzet','Notes'],...recoveryAttempts.map(x=>{const c=activeCalls.find(c=>c.id===x.call_id)||{},v=vmap[x.visit_id]||{};return[x.id,x.call_id,x.visit_id,v.visit_date||'',pmap[x.jovis_user_id]?.display_name||'',c.outlet_id||'',c.outlet_name||'',c.result==='NON_EC'?observedLabel(c,taxonomy,language):'',x.attempted_at||'',x.channel||'',x.outcome||'',x.outcome==='RECOVERED_EC'?num(x.omzet):'',x.notes||'']})];
  const photoRows=[['Photo ID','Call ID','JOVIS','Kode Toko','Nama Toko','Photo Type','Caption','Storage Path','Mime Type','Size Bytes','Created At'],...photos.map(x=>{const c=activeCalls.find(c=>c.id===x.call_id)||{};return[x.id,x.call_id,pmap[x.jovis_user_id]?.display_name||'',c.outlet_id||'',c.outlet_name||'',x.photo_type||'',x.caption||'',x.storage_path||'',x.mime_type||'',x.size_bytes??'',x.created_at||'']})];

  const recoveredUnique=Object.values(recoveredByCall),waCalls=activeCalls.filter(c=>method(c)==='WHATSAPP');
  const durations=activeCalls.filter(c=>method(c)==='VISIT').map(c=>Number(c.duration_seconds)).filter(Number.isFinite),ecDur=activeCalls.filter(c=>method(c)==='VISIT'&&c.result==='EC').map(c=>Number(c.duration_seconds)).filter(Number.isFinite),neDur=activeCalls.filter(c=>method(c)==='VISIT'&&c.result==='NON_EC').map(c=>Number(c.duration_seconds)).filter(Number.isFinite);
  const summary=[[`Field Visit Intelligence v${APP_VERSION}`],['Visits',visits.length],['Visit SC',a.sc],['Visit EC',a.ec],['Visit EC/SC %',a.ecsc],['Visit Non-EC',a.ne],['Visit Omzet',a.totalRevenue],['Pure WA EC',waCalls.length],['Pure WA Omzet',waCalls.reduce((s,c)=>s+num(c.omzet),0)],['Recovered EC',recoveredUnique.length],['Recovered Omzet',recoveredUnique.reduce((s,x)=>s+num(x.omzet),0)],['SFA Exact Coverage %',a.sfaCoverage],['Mismatch',a.status.MISMATCH],['Taxonomy Gap',a.status.TAXONOMY_GAP],['Calls with Duration',durations.length],['Avg Visit Duration Seconds',avg(durations)??''],['Avg EC Duration Seconds',avg(ecDur)??''],['Avg Non-EC Duration Seconds',avg(neDur)??''],['Reason Detail Rows',reasonDetails.length],['Stock Item Rows',stockItems.length],['Recovery Attempt Rows',recoveryAttempts.length],['Photo Evidence Rows',photos.length]];
  const dict=[['Field','Meaning'],['Call Method','VISIT = physical call with GPS; WHATSAPP = pure EC without physical visit'],['Visit EC/SC','Only physical VISIT calls are included in denominator/numerator'],['Recovered EC','Post-visit recovery event; original Non-EC is preserved'],['Recoverable Today','Observer classification YES/NO/UNKNOWN for same-day chance'],['Salesman Oversized/Bombing Claim','Salesman statement only; not proof. Validate against historical order database'],['Photo Evidence','Private Supabase Storage metadata; storage path is exported, not a public URL'],['SFA Reason Exact','Exact wording available in E-Work'],['Observed Real Reason','Independent field observation taxonomy'],['Check-in GPS','Required for VISIT; not applicable for pure WHATSAPP EC']];

  const xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">${sheet('00_Summary',summary)}${sheet('01_RAW_CALL_LOG',rawRows)}${sheet('02_NON_EC_DETAIL',nonEc)}${sheet('03_REASON_ACCURACY',acc)}${sheet('04_MISMATCH_MATRIX',matrix)}${sheet('05_UNMAPPED_REASONS',unmapped)}${sheet('06_FOLLOW_UP',follow)}${sheet('07_VISIT_SUMMARY',vs)}${sheet('08_DATA_DICTIONARY',dict)}${sheet('09_DWELL_TIME_GPS',dwell)}${sheet('10_SFA_RECOVERY',sfaRecovery)}${sheet('11_REASON_DETAIL',reasonDetailRows)}${sheet('12_STOCK_CHECK',stockRows)}${sheet('13_RECOVERY_ATTEMPTS',recoveryRows)}${sheet('14_PHOTO_EVIDENCE',photoRows)}</Workbook>`;
  return {filename:`FVI_Consolidated_Detail_${new Date().toISOString().slice(0,10)}.xls`,xml};
}
export function exportDetailedExcel(input){const out=buildDetailedWorkbook(input);download(out.filename,out.xml,'application/vnd.ms-excel')}
export function exportJsonBackup(payload){download(`FVI_Backup_${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(payload,null,2),'application/json')}
