import { APP_VERSION } from '../config/app-config.js';
import { analyze, observedLabel, sfaLabel } from '../domain/analysis-engine.js';
import { num } from '../config/utils.js';

function download(name,content,type='text/plain;charset=utf-8'){
  const blob=new Blob([content],{type});const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);
}
function xmlEscape(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function cell(v){const type=typeof v==='number'?'Number':'String';return `<Cell><Data ss:Type="${type}">${xmlEscape(v)}</Data></Cell>`}
function sheet(name,rows){return `<Worksheet ss:Name="${name.slice(0,31).replace(/[\\/?*\[\]:]/g,'_')}"><Table>${rows.map(r=>`<Row>${r.map(cell).join('')}</Row>`).join('')}</Table></Worksheet>`}
const avg=values=>{const v=values.filter(x=>Number.isFinite(x)&&x>=0);return v.length?v.reduce((s,x)=>s+x,0)/v.length:null};

export function buildDetailedWorkbook({visits,calls,taxonomy,profiles=[],language='id'}){
  const a=analyze(visits,calls,taxonomy,language);const pmap=Object.fromEntries(profiles.map(p=>[p.id,p]));const vmap=Object.fromEntries(visits.map(v=>[v.id,v]));
  const activeCalls=calls.filter(x=>!x.is_deleted);
  const rawHeader=['Visit ID','Call ID','Visit Date','JOVIS','JOVIS User ID','Depot','Salesman','Salesman ID','Visit Start Time','Visit End Time','Visit Status','Call Timestamp (Legacy)','Check-in At','Checkout At','Duration Seconds','Duration Minutes','Check-in Latitude','Check-in Longitude','Check-in Accuracy (m)','Checkout Latitude','Checkout Longitude','Checkout Accuracy (m)','Last Edited At','Kode Toko','Nama Toko','JKS / Off Route','Result','Omzet EC','Observed Real Reason','Observed Reason Code','Custom Real Reason','Contributing Factor','Evidence','SFA Reason','SFA Reason Code','Reason Match Status','Why SFA Reason Selected','Planned Revisit','Can Revisit Earlier','Reason Determining Follow-up Timing','Quick Note','Created At','Updated At'];
  const rawRow=c=>{const v=vmap[c.visit_id]||{};const p=pmap[c.jovis_user_id]||{};const dur=Number(c.duration_seconds);return [v.id||c.visit_id,c.id,v.visit_date||'',p.display_name||v.jovis_name||'',c.jovis_user_id,v.depot||'',v.salesman_name||'',v.salesman_id||'',v.start_time||'',v.end_time||'',v.status||'',c.call_timestamp||'',c.checkin_at||'',c.checkout_at||'',Number.isFinite(dur)?dur:'',Number.isFinite(dur)?dur/60:'',c.checkin_latitude??'',c.checkin_longitude??'',c.checkin_accuracy_m??'',c.checkout_latitude??'',c.checkout_longitude??'',c.checkout_accuracy_m??'',c.client_updated_at||c.updated_at||'',c.outlet_id||'',c.outlet_name||'',c.route_status||'',c.result||'',num(c.omzet),observedLabel(c,taxonomy,language),c.observed_reason_code||'',c.custom_real_reason||'',c.contributing_factor||'',c.evidence||'',sfaLabel(c,taxonomy,language),c.sfa_reason_code||'',c.reason_match_status||'',c.sfa_selection_reason||'',c.revisit_plan||'',c.can_revisit_earlier||'',c.followup_timing_reason||'',c.quick_note||'',c.created_at||'',c.updated_at||'']};
  const rawRows=[rawHeader,...activeCalls.map(rawRow)];
  const nonEc=[rawHeader,...activeCalls.filter(c=>c.result==='NON_EC').map(rawRow)];
  const acc=[['SFA Reason','Cases','Match','Partial','Mismatch','Unclear','Exact Match %','Mismatch %'],...Object.entries(a.bySfa).map(([code,x])=>[taxonomy.find(r=>r.reason_code===code)?.reason_label_id||code,x.n,x.MATCH,x.PARTIAL,x.MISMATCH,x.UNCLEAR,x.exactRate,x.mismatchRate])];
  const okeys=Object.keys(a.observedCounts),skeys=Object.keys(a.sfaCounts);const matrix=[['SFA \\ Actual',...okeys.map(k=>a.observedLabels[k]||k)],...skeys.map(s=>[taxonomy.find(r=>r.reason_code===s)?.reason_label_id||s,...okeys.map(o=>a.matrix[s]?.[o]||0)])];
  const unmappedHeader=['Raw Actual Reason','Frequency','Current SFA Reasons','JOVIS','Depot','Salesman','Kode Toko','Nama Toko','Evidence','Check-in At','Duration Seconds','Visit ID','Call ID'];const unmapped=[unmappedHeader];
  for(const cr of Object.values(a.customReasons).sort((x,y)=>y.count-x.count)){for(const c of cr.cases){const v=vmap[c.visit_id]||{},p=pmap[c.jovis_user_id]||{};unmapped.push([cr.label,cr.count,sfaLabel(c,taxonomy,language),p.display_name||'',v.depot||'',v.salesman_name||'',c.outlet_id||'',c.outlet_name||'',c.evidence||'',c.checkin_at||c.call_timestamp||'',c.duration_seconds??'',c.visit_id,c.id])}}
  const follow=[['Visit ID','Call ID','JOVIS','Depot','Salesman','Kode Toko','Nama Toko','Observed Reason','SFA Reason','Reason Match','Planned Revisit','Can Revisit Earlier','Reason Determining Timing','Evidence','Check-in At','Checkout At','Duration Seconds'],...activeCalls.filter(c=>c.result==='NON_EC').map(c=>{const v=vmap[c.visit_id]||{},p=pmap[c.jovis_user_id]||{};return[c.visit_id,c.id,p.display_name||'',v.depot||'',v.salesman_name||'',c.outlet_id||'',c.outlet_name||'',observedLabel(c,taxonomy,language),sfaLabel(c,taxonomy,language),c.reason_match_status||'',c.revisit_plan||'',c.can_revisit_earlier||'',c.followup_timing_reason||'',c.evidence||'',c.checkin_at||'',c.checkout_at||'',c.duration_seconds??'']})];
  const vs=[['Visit ID','Date','JOVIS','Depot','Salesman','Start','End','Status','SC','EC','Non-EC','EC/SC %','Total Omzet','Avg Duration Seconds'],...a.visitSummaries.map(x=>{const vc=activeCalls.filter(c=>c.visit_id===x.visit.id),d=avg(vc.map(c=>Number(c.duration_seconds)));return[x.visit.id,x.visit.visit_date,pmap[x.visit.jovis_user_id]?.display_name||'',x.visit.depot,x.visit.salesman_name,x.visit.start_time,x.visit.end_time||'',x.visit.status,x.sc,x.ec,x.ne,x.ecsc,x.revenue,d??'']})];
  const dwell=[['Visit ID','Call ID','Date','JOVIS','Depot','Salesman','Kode Toko','Nama Toko','Result','Check-in At','Checkout At','Duration Seconds','Duration Minutes','Check-in Latitude','Check-in Longitude','Check-in Accuracy (m)','Checkout Latitude','Checkout Longitude','Checkout Accuracy (m)'],...activeCalls.map(c=>{const v=vmap[c.visit_id]||{},p=pmap[c.jovis_user_id]||{},d=Number(c.duration_seconds);return[c.visit_id,c.id,v.visit_date||'',p.display_name||'',v.depot||'',v.salesman_name||'',c.outlet_id||'',c.outlet_name||'',c.result||'',c.checkin_at||'',c.checkout_at||'',Number.isFinite(d)?d:'',Number.isFinite(d)?d/60:'',c.checkin_latitude??'',c.checkin_longitude??'',c.checkin_accuracy_m??'',c.checkout_latitude??'',c.checkout_longitude??'',c.checkout_accuracy_m??'']})];
  const durations=activeCalls.map(c=>Number(c.duration_seconds)).filter(Number.isFinite),ecDur=activeCalls.filter(c=>c.result==='EC').map(c=>Number(c.duration_seconds)).filter(Number.isFinite),neDur=activeCalls.filter(c=>c.result==='NON_EC').map(c=>Number(c.duration_seconds)).filter(Number.isFinite);
  const dict=[['Field','Meaning'],['Visit ID','Unique field visit identifier'],['Call ID','Unique call identifier'],['JOVIS','Authenticated observer account'],['Kode Toko','Canonical store code. UI automatically prefixes C and accepts numeric digits only. Example: C9899421'],['Check-in At','Timestamp captured when JOVIS presses Check In Call after mandatory browser geolocation succeeds'],['Checkout At','Timestamp captured when JOVIS saves/finishes the call after checkout geolocation succeeds'],['Duration Seconds','Checkout At minus Check-in At'],['Check-in / Checkout Coordinates','Browser geolocation latitude/longitude plus reported accuracy in meters'],['Call Timestamp (Legacy)','Backward-compatible call timestamp; new calls use Check-in At'],['Observed Real Reason','Primary actual Non-EC reason observed in the outlet'],['Custom Real Reason','Mandatory free text when Observed Reason = Other; preserved for taxonomy discovery'],['Contributing Factor','Optional secondary factor; does not replace primary actual reason'],['SFA Reason','Reason selected by salesman in SFA/E-Work'],['Reason Match Status','MATCH / PARTIAL / MISMATCH / UNCLEAR'],['Evidence','Factual observation or statement supporting the actual reason'],['Planned Revisit','Planned follow-up timing'],['Can Revisit Earlier','Whether the outlet can be revisited earlier than the selected plan'],['Reason Determining Follow-up Timing','Operational reason or signal determining the revisit timing'],['Omzet EC','Transaction/order value for EC; mandatory'],['Last Edited At','Latest client edit timestamp; original check-in / checkout timestamps are preserved when editing existing calls']];
  const summary=[[`Field Visit Intelligence v${APP_VERSION}`],['Visits',visits.length],['SC',a.sc],['EC',a.ec],['EC/SC %',a.ecsc],['Non-EC',a.ne],['Total Omzet',a.totalRevenue],['Avg Omzet / EC',a.avgRevenueEc],['Exact Match %',a.exactRate],['Mismatch %',a.mismatchRate],['Unmapped Real Reason Cases',Object.values(a.customReasons).reduce((s,x)=>s+x.count,0)],['Calls with Duration',durations.length],['Avg Duration Seconds',avg(durations)??''],['Avg EC Duration Seconds',avg(ecDur)??''],['Avg Non-EC Duration Seconds',avg(neDur)??'']];
  const xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">${sheet('00_Summary',summary)}${sheet('01_RAW_CALL_LOG',rawRows)}${sheet('02_NON_EC_DETAIL',nonEc)}${sheet('03_REASON_ACCURACY',acc)}${sheet('04_MISMATCH_MATRIX',matrix)}${sheet('05_UNMAPPED_REASONS',unmapped)}${sheet('06_FOLLOW_UP',follow)}${sheet('07_VISIT_SUMMARY',vs)}${sheet('08_DATA_DICTIONARY',dict)}${sheet('09_DWELL_TIME_GPS',dwell)}</Workbook>`;
  return {filename:`FVI_Consolidated_Detail_${new Date().toISOString().slice(0,10)}.xls`,xml};
}

export function exportDetailedExcel(input){const out=buildDetailedWorkbook(input);download(out.filename,out.xml,'application/vnd.ms-excel')}
export function exportJsonBackup(payload){download(`FVI_Backup_${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(payload,null,2),'application/json')}
