import { analyze, observedLabel, sfaLabel } from '../domain/analysis-engine.js';
import { fmtCurrency, pct, num } from '../config/utils.js';

function download(name,content,type='text/plain;charset=utf-8'){
  const blob=new Blob([content],{type});const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);
}
function xmlEscape(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function cell(v){const type=typeof v==='number'?'Number':'String';return `<Cell><Data ss:Type="${type}">${xmlEscape(v)}</Data></Cell>`}
function sheet(name,rows){return `<Worksheet ss:Name="${name.slice(0,31).replace(/[\\/?*\[\]:]/g,'_')}"><Table>${rows.map(r=>`<Row>${r.map(cell).join('')}</Row>`).join('')}</Table></Worksheet>`}

export function buildDetailedWorkbook({visits,calls,taxonomy,profiles=[],language='id'}){
  const a=analyze(visits,calls,taxonomy,language);const pmap=Object.fromEntries(profiles.map(p=>[p.id,p]));const vmap=Object.fromEntries(visits.map(v=>[v.id,v]));
  const rawHeader=['Visit ID','Call ID','Visit Date','JOVIS','JOVIS User ID','Depot','Salesman','Salesman ID','Visit Start Time','Visit End Time','Visit Status','Call Timestamp','Last Edited At','Outlet ID','Outlet Name','JKS / Off Route','Result','Omzet EC','Observed Real Reason','Observed Reason Code','Custom Real Reason','Contributing Factor','Evidence','SFA Reason','SFA Reason Code','Reason Match Status','Why SFA Reason Selected','Planned Revisit','Can Revisit Earlier','Reason Determining Follow-up Timing','Quick Note','Created At','Updated At'];
  const rawRows=[rawHeader];
  for(const c of calls.filter(x=>!x.is_deleted)){const v=vmap[c.visit_id]||{};const p=pmap[c.jovis_user_id]||{};rawRows.push([v.id||c.visit_id,c.id,v.visit_date||'',p.display_name||v.jovis_name||'',c.jovis_user_id,v.depot||'',v.salesman_name||'',v.salesman_id||'',v.start_time||'',v.end_time||'',v.status||'',c.call_timestamp||'',c.client_updated_at||c.updated_at||'',c.outlet_id||'',c.outlet_name||'',c.route_status||'',c.result||'',num(c.omzet),observedLabel(c,taxonomy,language),c.observed_reason_code||'',c.custom_real_reason||'',c.contributing_factor||'',c.evidence||'',sfaLabel(c,taxonomy,language),c.sfa_reason_code||'',c.reason_match_status||'',c.sfa_selection_reason||'',c.revisit_plan||'',c.can_revisit_earlier||'',c.followup_timing_reason||'',c.quick_note||'',c.created_at||'',c.updated_at||''])}
  const nonEc=[rawHeader,...rawRows.slice(1).filter(r=>r[16]==='NON_EC')];
  const acc=[['SFA Reason','Cases','Match','Partial','Mismatch','Unclear','Exact Match %','Mismatch %'],...Object.entries(a.bySfa).map(([code,x])=>[taxonomy.find(r=>r.reason_code===code)?.reason_label_id||code,x.n,x.MATCH,x.PARTIAL,x.MISMATCH,x.UNCLEAR,x.exactRate,x.mismatchRate])];
  const okeys=Object.keys(a.observedCounts),skeys=Object.keys(a.sfaCounts);const matrix=[['SFA \\ Actual',...okeys.map(k=>a.observedLabels[k]||k)],...skeys.map(s=>[taxonomy.find(r=>r.reason_code===s)?.reason_label_id||s,...okeys.map(o=>a.matrix[s]?.[o]||0)])];
  const unmappedHeader=['Raw Actual Reason','Frequency','Current SFA Reasons','JOVIS','Depot','Salesman','Outlet','Evidence','Call Timestamp','Visit ID','Call ID'];const unmapped=[unmappedHeader];
  for(const cr of Object.values(a.customReasons).sort((x,y)=>y.count-x.count)){for(const c of cr.cases){const v=vmap[c.visit_id]||{},p=pmap[c.jovis_user_id]||{};unmapped.push([cr.label,cr.count,sfaLabel(c,taxonomy,language),p.display_name||'',v.depot||'',v.salesman_name||'',c.outlet_name||'',c.evidence||'',c.call_timestamp||'',c.visit_id,c.id])}}
  const follow=[['Visit ID','Call ID','JOVIS','Depot','Salesman','Outlet','Observed Reason','SFA Reason','Reason Match','Planned Revisit','Can Revisit Earlier','Reason Determining Timing','Evidence'],...calls.filter(c=>!c.is_deleted&&c.result==='NON_EC').map(c=>{const v=vmap[c.visit_id]||{},p=pmap[c.jovis_user_id]||{};return[c.visit_id,c.id,p.display_name||'',v.depot||'',v.salesman_name||'',c.outlet_name||'',observedLabel(c,taxonomy,language),sfaLabel(c,taxonomy,language),c.reason_match_status||'',c.revisit_plan||'',c.can_revisit_earlier||'',c.followup_timing_reason||'',c.evidence||'']})];
  const vs=[['Visit ID','Date','JOVIS','Depot','Salesman','Start','End','Status','SC','EC','Non-EC','EC/SC %','Total Omzet'],...a.visitSummaries.map(x=>[x.visit.id,x.visit.visit_date,pmap[x.visit.jovis_user_id]?.display_name||'',x.visit.depot,x.visit.salesman_name,x.visit.start_time,x.visit.end_time||'',x.visit.status,x.sc,x.ec,x.ne,x.ecsc,x.revenue])];
  const dict=[['Field','Meaning'],['Visit ID','Unique field visit identifier'],['Call ID','Unique call identifier'],['JOVIS','Authenticated observer account'],['Observed Real Reason','Primary actual Non-EC reason observed in the outlet'],['Custom Real Reason','Mandatory free text when Observed Reason = Other; preserved for taxonomy discovery'],['Contributing Factor','Optional secondary factor; does not replace primary actual reason'],['SFA Reason','Reason selected by salesman in SFA/E-Work'],['Reason Match Status','MATCH / PARTIAL / MISMATCH / UNCLEAR'],['Evidence','Factual observation or statement supporting the actual reason'],['Planned Revisit','Planned follow-up timing'],['Can Revisit Earlier','Whether the outlet can be revisited earlier than the selected plan'],['Reason Determining Follow-up Timing','Operational reason or signal determining the revisit timing'],['Omzet EC','Transaction/order value for EC; mandatory in v0.3'],['Call Timestamp','Timestamp captured when the result is first saved'],['Last Edited At','Latest client edit timestamp; original call timestamp is preserved']];
  const summary=[['Field Visit Intelligence v0.3.2'],['Visits',visits.length],['SC',a.sc],['EC',a.ec],['EC/SC %',a.ecsc],['Non-EC',a.ne],['Total Omzet',a.totalRevenue],['Avg Omzet / EC',a.avgRevenueEc],['Exact Match %',a.exactRate],['Mismatch %',a.mismatchRate],['Unmapped Real Reason Cases',Object.values(a.customReasons).reduce((s,x)=>s+x.count,0)]];
  const xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">${sheet('00_Summary',summary)}${sheet('01_RAW_CALL_LOG',rawRows)}${sheet('02_NON_EC_DETAIL',nonEc)}${sheet('03_REASON_ACCURACY',acc)}${sheet('04_MISMATCH_MATRIX',matrix)}${sheet('05_UNMAPPED_REASONS',unmapped)}${sheet('06_FOLLOW_UP',follow)}${sheet('07_VISIT_SUMMARY',vs)}${sheet('08_DATA_DICTIONARY',dict)}</Workbook>`;
  return {filename:`FVI_Consolidated_Detail_${new Date().toISOString().slice(0,10)}.xls`,xml};
}

export function exportDetailedExcel(input){const out=buildDetailedWorkbook(input);download(out.filename,out.xml,'application/vnd.ms-excel')}

export function exportJsonBackup(payload){download(`FVI_Backup_${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(payload,null,2),'application/json')}
